services:
  api:
    build:
      context: .
      target: api
    environment:
      LOG_FORMAT: json
      DATABASE_URL: postgres://notification:notification@postgres:5432/notification
    ports:
      - '3000:3000'
    stop_grace_period: 35s

  worker:
    build:
      context: .
      target: worker
    environment:
      LOG_FORMAT: json
      DATABASE_URL: postgres://notification:notification@postgres:5432/notification
    stop_grace_period: 35s
